on: push

permissions:
  contents: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'
    - name: node version
      run: node -v
    - name: install modules
      run: cd frontend && npm install -g npm@6.14.14 && npm install -g @vue/cli && npm install
    - name: build
      run: pwd && npm run build
